USE [{0}]
GO
SET XACT_ABORT ON
BEGIN TRAN
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (1, 'bigint', 0, 0, '64 bit signed integer')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (2, 'binary', 1, 0, 'Binary data')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (3, 'bit', 0, 0, 'Boolean value')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (4, 'char', 1, 0, 'One byte character string, fixed length')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (5, 'datetime', 0, 0, 'Data and time')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (6, 'decimal', 0, 1, 'Fixed point number')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (7, 'float', 0, 1, 'Floating point number, bit length of mantissa specified')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (8, 'int', 0, 0, '32 bit signed integer')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (9, 'money', 0, 0, 'Fixed point number for money')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (10, 'nchar', 1, 0, 'Unicode character string, fixed length')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (11, 'nvarchar', 1, 0, 'Unicode character string, variable length')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (12, 'ntext', 1, 0, 'Large unicode text')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (13, 'numeric', 0, 1, 'Fixed point number, same to decimal')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (14, 'real', 0, 0, 'Floating point number, same to Float(24)')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (15, 'smalldatetime', 0, 0, 'Date and time, in short form')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (16, 'smallint', 0, 0, '16 bit signed integer')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (17, 'smallmoney', 0, 0, 'Fixed point number for money with small range')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (18, 'sql_variant', 0, 0, 'SQL Variant data type')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (19, 'sysname', 0, 0, 'SQL Server system name data type, same to nvarchar(128)')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (20, 'text', 1, 0, 'Large one byte text')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (21, 'timestamp', 0, 0, 'Special timestamp value, same to binary(8) if not null and varbinary(8) otherwise')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (22, 'tinyint', 0, 0, '8 bit signed integer')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (23, 'uniqueidentifier', 0, 0, 'GUID value')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (24, 'varbinary', 1, 0, 'Binary data, variable length')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (25, 'varchar', 1, 0, 'Unicode character string, variable length')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (26, 'xml', 0, 0, 'XML data')
INSERT INTO Metadata_DataType (ID, [Name], HasLength, HasPrecisionAndScale, Description)
VALUES (27, 'image', 1, 0, 'Binary data')
COMMIT TRAN
GO