//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace JetBat.Silverlight.UI.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alexshestakov.com/", ConfigurationName="WebService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://alexshestakov.com/Authenticate", ReplyAction="*")]
        System.IAsyncResult BeginAuthenticate(JetBat.Silverlight.UI.WebService.AuthenticateRequest request, System.AsyncCallback callback, object asyncState);
        
        JetBat.Silverlight.UI.WebService.AuthenticateResponse EndAuthenticate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://alexshestakov.com/ExecuteMethod", ReplyAction="*")]
        System.IAsyncResult BeginExecuteMethod(JetBat.Silverlight.UI.WebService.ExecuteMethodRequest request, System.AsyncCallback callback, object asyncState);
        
        JetBat.Silverlight.UI.WebService.ExecuteMethodResponse EndExecuteMethod(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://alexshestakov.com/BulkExecute", ReplyAction="*")]
        System.IAsyncResult BeginBulkExecute(JetBat.Silverlight.UI.WebService.BulkExecuteRequest request, System.AsyncCallback callback, object asyncState);
        
        JetBat.Silverlight.UI.WebService.BulkExecuteResponse EndBulkExecute(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://alexshestakov.com/GetObjectDefinition", ReplyAction="*")]
        System.IAsyncResult BeginGetObjectDefinition(JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequest request, System.AsyncCallback callback, object asyncState);
        
        JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponse EndGetObjectDefinition(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(JetBat.Silverlight.UI.WebService.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(JetBat.Silverlight.UI.WebService.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteMethod", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.ExecuteMethodRequestBody Body;
        
        public ExecuteMethodRequest() {
        }
        
        public ExecuteMethodRequest(JetBat.Silverlight.UI.WebService.ExecuteMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class ExecuteMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectNamespace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string methodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parametersSerialized;
        
        public ExecuteMethodRequestBody() {
        }
        
        public ExecuteMethodRequestBody(string objectNamespace, string objectName, string methodName, string parametersSerialized) {
            this.objectNamespace = objectNamespace;
            this.objectName = objectName;
            this.methodName = methodName;
            this.parametersSerialized = parametersSerialized;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteMethodResponse", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.ExecuteMethodResponseBody Body;
        
        public ExecuteMethodResponse() {
        }
        
        public ExecuteMethodResponse(JetBat.Silverlight.UI.WebService.ExecuteMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class ExecuteMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteMethodResult;
        
        public ExecuteMethodResponseBody() {
        }
        
        public ExecuteMethodResponseBody(string ExecuteMethodResult) {
            this.ExecuteMethodResult = ExecuteMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BulkExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BulkExecute", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.BulkExecuteRequestBody Body;
        
        public BulkExecuteRequest() {
        }
        
        public BulkExecuteRequest(JetBat.Silverlight.UI.WebService.BulkExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class BulkExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string methodCallArgumentsListSerialized;
        
        public BulkExecuteRequestBody() {
        }
        
        public BulkExecuteRequestBody(string methodCallArgumentsListSerialized) {
            this.methodCallArgumentsListSerialized = methodCallArgumentsListSerialized;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BulkExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BulkExecuteResponse", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.BulkExecuteResponseBody Body;
        
        public BulkExecuteResponse() {
        }
        
        public BulkExecuteResponse(JetBat.Silverlight.UI.WebService.BulkExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class BulkExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BulkExecuteResult;
        
        public BulkExecuteResponseBody() {
        }
        
        public BulkExecuteResponseBody(string BulkExecuteResult) {
            this.BulkExecuteResult = BulkExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectDefinitionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectDefinition", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequestBody Body;
        
        public GetObjectDefinitionRequest() {
        }
        
        public GetObjectDefinitionRequest(JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class GetObjectDefinitionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string objectNamespace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string objectName;
        
        public GetObjectDefinitionRequestBody() {
        }
        
        public GetObjectDefinitionRequestBody(string objectType, string objectNamespace, string objectName) {
            this.objectType = objectType;
            this.objectNamespace = objectNamespace;
            this.objectName = objectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectDefinitionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectDefinitionResponse", Namespace="http://alexshestakov.com/", Order=0)]
        public JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponseBody Body;
        
        public GetObjectDefinitionResponse() {
        }
        
        public GetObjectDefinitionResponse(JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://alexshestakov.com/")]
    public partial class GetObjectDefinitionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetObjectDefinitionResult;
        
        public GetObjectDefinitionResponseBody() {
        }
        
        public GetObjectDefinitionResponseBody(string GetObjectDefinitionResult) {
            this.GetObjectDefinitionResult = GetObjectDefinitionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : JetBat.Silverlight.UI.WebService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExecuteMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BulkExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BulkExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetObjectDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetObjectDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<JetBat.Silverlight.UI.WebService.ServiceSoap>, JetBat.Silverlight.UI.WebService.ServiceSoap {
        
        private BeginOperationDelegate onBeginAuthenticateDelegate;
        
        private EndOperationDelegate onEndAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginExecuteMethodDelegate;
        
        private EndOperationDelegate onEndExecuteMethodDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteMethodCompletedDelegate;
        
        private BeginOperationDelegate onBeginBulkExecuteDelegate;
        
        private EndOperationDelegate onEndBulkExecuteDelegate;
        
        private System.Threading.SendOrPostCallback onBulkExecuteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetObjectDefinitionDelegate;
        
        private EndOperationDelegate onEndGetObjectDefinitionDelegate;
        
        private System.Threading.SendOrPostCallback onGetObjectDefinitionCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
        
        public event System.EventHandler<ExecuteMethodCompletedEventArgs> ExecuteMethodCompleted;
        
        public event System.EventHandler<BulkExecuteCompletedEventArgs> BulkExecuteCompleted;
        
        public event System.EventHandler<GetObjectDefinitionCompletedEventArgs> GetObjectDefinitionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult JetBat.Silverlight.UI.WebService.ServiceSoap.BeginAuthenticate(JetBat.Silverlight.UI.WebService.AuthenticateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAuthenticate(string username, string password, System.AsyncCallback callback, object asyncState) {
            JetBat.Silverlight.UI.WebService.AuthenticateRequest inValue = new JetBat.Silverlight.UI.WebService.AuthenticateRequest();
            inValue.Body = new JetBat.Silverlight.UI.WebService.AuthenticateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).BeginAuthenticate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JetBat.Silverlight.UI.WebService.AuthenticateResponse JetBat.Silverlight.UI.WebService.ServiceSoap.EndAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndAuthenticate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndAuthenticate(System.IAsyncResult result) {
            JetBat.Silverlight.UI.WebService.AuthenticateResponse retVal = ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).EndAuthenticate(result);
            return retVal.Body.AuthenticateResult;
        }
        
        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginAuthenticate(username, password, callback, asyncState);
        }
        
        private object[] OnEndAuthenticate(System.IAsyncResult result) {
            bool retVal = this.EndAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateCompleted(object state) {
            if ((this.AuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateAsync(string username, string password) {
            this.AuthenticateAsync(username, password, null);
        }
        
        public void AuthenticateAsync(string username, string password, object userState) {
            if ((this.onBeginAuthenticateDelegate == null)) {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null)) {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null)) {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                        username,
                        password}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult JetBat.Silverlight.UI.WebService.ServiceSoap.BeginExecuteMethod(JetBat.Silverlight.UI.WebService.ExecuteMethodRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteMethod(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginExecuteMethod(string objectNamespace, string objectName, string methodName, string parametersSerialized, System.AsyncCallback callback, object asyncState) {
            JetBat.Silverlight.UI.WebService.ExecuteMethodRequest inValue = new JetBat.Silverlight.UI.WebService.ExecuteMethodRequest();
            inValue.Body = new JetBat.Silverlight.UI.WebService.ExecuteMethodRequestBody();
            inValue.Body.objectNamespace = objectNamespace;
            inValue.Body.objectName = objectName;
            inValue.Body.methodName = methodName;
            inValue.Body.parametersSerialized = parametersSerialized;
            return ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).BeginExecuteMethod(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JetBat.Silverlight.UI.WebService.ExecuteMethodResponse JetBat.Silverlight.UI.WebService.ServiceSoap.EndExecuteMethod(System.IAsyncResult result) {
            return base.Channel.EndExecuteMethod(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndExecuteMethod(System.IAsyncResult result) {
            JetBat.Silverlight.UI.WebService.ExecuteMethodResponse retVal = ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).EndExecuteMethod(result);
            return retVal.Body.ExecuteMethodResult;
        }
        
        private System.IAsyncResult OnBeginExecuteMethod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string objectNamespace = ((string)(inValues[0]));
            string objectName = ((string)(inValues[1]));
            string methodName = ((string)(inValues[2]));
            string parametersSerialized = ((string)(inValues[3]));
            return this.BeginExecuteMethod(objectNamespace, objectName, methodName, parametersSerialized, callback, asyncState);
        }
        
        private object[] OnEndExecuteMethod(System.IAsyncResult result) {
            string retVal = this.EndExecuteMethod(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteMethodCompleted(object state) {
            if ((this.ExecuteMethodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteMethodCompleted(this, new ExecuteMethodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteMethodAsync(string objectNamespace, string objectName, string methodName, string parametersSerialized) {
            this.ExecuteMethodAsync(objectNamespace, objectName, methodName, parametersSerialized, null);
        }
        
        public void ExecuteMethodAsync(string objectNamespace, string objectName, string methodName, string parametersSerialized, object userState) {
            if ((this.onBeginExecuteMethodDelegate == null)) {
                this.onBeginExecuteMethodDelegate = new BeginOperationDelegate(this.OnBeginExecuteMethod);
            }
            if ((this.onEndExecuteMethodDelegate == null)) {
                this.onEndExecuteMethodDelegate = new EndOperationDelegate(this.OnEndExecuteMethod);
            }
            if ((this.onExecuteMethodCompletedDelegate == null)) {
                this.onExecuteMethodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteMethodCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteMethodDelegate, new object[] {
                        objectNamespace,
                        objectName,
                        methodName,
                        parametersSerialized}, this.onEndExecuteMethodDelegate, this.onExecuteMethodCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult JetBat.Silverlight.UI.WebService.ServiceSoap.BeginBulkExecute(JetBat.Silverlight.UI.WebService.BulkExecuteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBulkExecute(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginBulkExecute(string methodCallArgumentsListSerialized, System.AsyncCallback callback, object asyncState) {
            JetBat.Silverlight.UI.WebService.BulkExecuteRequest inValue = new JetBat.Silverlight.UI.WebService.BulkExecuteRequest();
            inValue.Body = new JetBat.Silverlight.UI.WebService.BulkExecuteRequestBody();
            inValue.Body.methodCallArgumentsListSerialized = methodCallArgumentsListSerialized;
            return ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).BeginBulkExecute(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JetBat.Silverlight.UI.WebService.BulkExecuteResponse JetBat.Silverlight.UI.WebService.ServiceSoap.EndBulkExecute(System.IAsyncResult result) {
            return base.Channel.EndBulkExecute(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndBulkExecute(System.IAsyncResult result) {
            JetBat.Silverlight.UI.WebService.BulkExecuteResponse retVal = ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).EndBulkExecute(result);
            return retVal.Body.BulkExecuteResult;
        }
        
        private System.IAsyncResult OnBeginBulkExecute(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string methodCallArgumentsListSerialized = ((string)(inValues[0]));
            return this.BeginBulkExecute(methodCallArgumentsListSerialized, callback, asyncState);
        }
        
        private object[] OnEndBulkExecute(System.IAsyncResult result) {
            string retVal = this.EndBulkExecute(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBulkExecuteCompleted(object state) {
            if ((this.BulkExecuteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BulkExecuteCompleted(this, new BulkExecuteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BulkExecuteAsync(string methodCallArgumentsListSerialized) {
            this.BulkExecuteAsync(methodCallArgumentsListSerialized, null);
        }
        
        public void BulkExecuteAsync(string methodCallArgumentsListSerialized, object userState) {
            if ((this.onBeginBulkExecuteDelegate == null)) {
                this.onBeginBulkExecuteDelegate = new BeginOperationDelegate(this.OnBeginBulkExecute);
            }
            if ((this.onEndBulkExecuteDelegate == null)) {
                this.onEndBulkExecuteDelegate = new EndOperationDelegate(this.OnEndBulkExecute);
            }
            if ((this.onBulkExecuteCompletedDelegate == null)) {
                this.onBulkExecuteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBulkExecuteCompleted);
            }
            base.InvokeAsync(this.onBeginBulkExecuteDelegate, new object[] {
                        methodCallArgumentsListSerialized}, this.onEndBulkExecuteDelegate, this.onBulkExecuteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult JetBat.Silverlight.UI.WebService.ServiceSoap.BeginGetObjectDefinition(JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetObjectDefinition(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetObjectDefinition(string objectType, string objectNamespace, string objectName, System.AsyncCallback callback, object asyncState) {
            JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequest inValue = new JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequest();
            inValue.Body = new JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequestBody();
            inValue.Body.objectType = objectType;
            inValue.Body.objectNamespace = objectNamespace;
            inValue.Body.objectName = objectName;
            return ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).BeginGetObjectDefinition(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponse JetBat.Silverlight.UI.WebService.ServiceSoap.EndGetObjectDefinition(System.IAsyncResult result) {
            return base.Channel.EndGetObjectDefinition(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetObjectDefinition(System.IAsyncResult result) {
            JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponse retVal = ((JetBat.Silverlight.UI.WebService.ServiceSoap)(this)).EndGetObjectDefinition(result);
            return retVal.Body.GetObjectDefinitionResult;
        }
        
        private System.IAsyncResult OnBeginGetObjectDefinition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string objectType = ((string)(inValues[0]));
            string objectNamespace = ((string)(inValues[1]));
            string objectName = ((string)(inValues[2]));
            return this.BeginGetObjectDefinition(objectType, objectNamespace, objectName, callback, asyncState);
        }
        
        private object[] OnEndGetObjectDefinition(System.IAsyncResult result) {
            string retVal = this.EndGetObjectDefinition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetObjectDefinitionCompleted(object state) {
            if ((this.GetObjectDefinitionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetObjectDefinitionCompleted(this, new GetObjectDefinitionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetObjectDefinitionAsync(string objectType, string objectNamespace, string objectName) {
            this.GetObjectDefinitionAsync(objectType, objectNamespace, objectName, null);
        }
        
        public void GetObjectDefinitionAsync(string objectType, string objectNamespace, string objectName, object userState) {
            if ((this.onBeginGetObjectDefinitionDelegate == null)) {
                this.onBeginGetObjectDefinitionDelegate = new BeginOperationDelegate(this.OnBeginGetObjectDefinition);
            }
            if ((this.onEndGetObjectDefinitionDelegate == null)) {
                this.onEndGetObjectDefinitionDelegate = new EndOperationDelegate(this.OnEndGetObjectDefinition);
            }
            if ((this.onGetObjectDefinitionCompletedDelegate == null)) {
                this.onGetObjectDefinitionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetObjectDefinitionCompleted);
            }
            base.InvokeAsync(this.onBeginGetObjectDefinitionDelegate, new object[] {
                        objectType,
                        objectNamespace,
                        objectName}, this.onEndGetObjectDefinitionDelegate, this.onGetObjectDefinitionCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override JetBat.Silverlight.UI.WebService.ServiceSoap CreateChannel() {
            return new ServiceSoapClientChannel(this);
        }
        
        private class ServiceSoapClientChannel : ChannelBase<JetBat.Silverlight.UI.WebService.ServiceSoap>, JetBat.Silverlight.UI.WebService.ServiceSoap {
            
            public ServiceSoapClientChannel(System.ServiceModel.ClientBase<JetBat.Silverlight.UI.WebService.ServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAuthenticate(JetBat.Silverlight.UI.WebService.AuthenticateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Authenticate", _args, callback, asyncState);
                return _result;
            }
            
            public JetBat.Silverlight.UI.WebService.AuthenticateResponse EndAuthenticate(System.IAsyncResult result) {
                object[] _args = new object[0];
                JetBat.Silverlight.UI.WebService.AuthenticateResponse _result = ((JetBat.Silverlight.UI.WebService.AuthenticateResponse)(base.EndInvoke("Authenticate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExecuteMethod(JetBat.Silverlight.UI.WebService.ExecuteMethodRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ExecuteMethod", _args, callback, asyncState);
                return _result;
            }
            
            public JetBat.Silverlight.UI.WebService.ExecuteMethodResponse EndExecuteMethod(System.IAsyncResult result) {
                object[] _args = new object[0];
                JetBat.Silverlight.UI.WebService.ExecuteMethodResponse _result = ((JetBat.Silverlight.UI.WebService.ExecuteMethodResponse)(base.EndInvoke("ExecuteMethod", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBulkExecute(JetBat.Silverlight.UI.WebService.BulkExecuteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("BulkExecute", _args, callback, asyncState);
                return _result;
            }
            
            public JetBat.Silverlight.UI.WebService.BulkExecuteResponse EndBulkExecute(System.IAsyncResult result) {
                object[] _args = new object[0];
                JetBat.Silverlight.UI.WebService.BulkExecuteResponse _result = ((JetBat.Silverlight.UI.WebService.BulkExecuteResponse)(base.EndInvoke("BulkExecute", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetObjectDefinition(JetBat.Silverlight.UI.WebService.GetObjectDefinitionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetObjectDefinition", _args, callback, asyncState);
                return _result;
            }
            
            public JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponse EndGetObjectDefinition(System.IAsyncResult result) {
                object[] _args = new object[0];
                JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponse _result = ((JetBat.Silverlight.UI.WebService.GetObjectDefinitionResponse)(base.EndInvoke("GetObjectDefinition", _args, result)));
                return _result;
            }
        }
    }
}
